on:
  push:
    branches: [ "main" ]

name: Build and Create Release

jobs:
  build:
    name: Build and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install packages
        run: |
          cd frontend/
          npm install
        
      - name: Build frontend/
        run: npm run build
        
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            backend/backend/*
            backend/manage.py
            backend/requirements.txt
            frontend/build/*
