on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Test Create Release

jobs:
  build:
    name: Create Release .zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install packages
        run: |
          cd frontend/
          npm install
        
      - name: Build frontend/
        # should copy the build/ directory to backend so that the static usr stuff works fine
        run: |
          cd frontend/
          npm run build 
          
      - name: Create release.zip
        run: |
          mkdir release && cd release
          mkdir backend && cd backend
          mkdir backend
          mkdir build
          cd ../../
          sed -i 's/DEBUG = True/DEBUG = False/I' backend/backend/settings.py
          sed -i 's/DEPLOYMENT_LINK = "http:\/\/localhost:3000"/DEPLOYMENT_LINK = "https:\/\/nouvique.pythonanywhere.com"/I' backend/backend/settings.py
          cp backend/backend/* release/backend/backend/
          cp backend/manage.py release/backend/
          cp backend/requirements.txt release/backend/
          cp -r backend/build/* release/backend/build/
          cp run_backend.sh release
          zip -r release.zip release
